name: update sigma folder

on:
  push:
    branches: [main]
    paths: "tax/**"

jobs:
  update-sigma:
    runs-on: ubuntu-latest
    steps:
      - name: checkout alpha
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ALPHA_TOKEN }}

      - name: push the changes to delta
        run: |
          # git config --global user.email "ps@odico.dk"
          # git config --global user.name "palaniappanodico"
          # git config pull.rebase false
          # git pull -s subtree https://github.com/palaniappanodico/incometax.git main --allow-unrelated-histories
          # git push
          git push https://github.com/palaniappanodico/incometax.git $(git subtree split --prefix=tax --onto=https://github.com/palaniappanodico/incometax.git/main):main
