name: update sigma folder

on:
  push:
    branches: [main]
    paths: "cars/**"

jobs:
  update-sigma:
    runs-on: ubuntu-latest
    steps:
      - name: checkout alpha
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ALPHA_TOKEN }}

      - name: push the changes to delta
        run: |
          # git merge --allow-unrelated-histories -X subtree=cars https://github.com/palaniappanodico/wheels.git main
          # git subtree pull --prefix cars https://github.com/palaniappanodico/wheels.git main --squash
          git config pull.rebase true
          git pull --squash -s subtree https://github.com/palaniappanodico/wheels.git main
          git subtree push --prefix cars https://github.com/palaniappanodico/wheels.git main --squash
