name: update sigma folder

on:
  push:
    branches: [main]
    paths: "tax/**"

jobs:
  update-sigma:
    runs-on: ubuntu-latest
    steps:
      - name: checkout alpha
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ALPHA_TOKEN }}

      - name: push the changes to delta
        run: |
          git config --global user.email "ps@odico.dk"
          git config --global user.name "palaniappanodico"
          git subtree pull --prefix tax https://github.com/palaniappanodico/incometax.git main --squash
          git subtree push --prefix tax https://github.com/palaniappanodico/incometax.git main
